/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * $Header:$
 */
// ------------------------------------------------------------------------------
//  Generated by WebLogic Workshop
// 
//  Created on: Thu Aug 07 09:17:50 MDT 2003
//  By: dolander
// -----------------------------------------------------------------------------
package bugs.b37374;
import org.apache.beehive.netui.pageflow.Forward;
import org.apache.beehive.netui.pageflow.PageFlowController;
import org.apache.beehive.netui.pageflow.annotations.Jpf;

import java.io.Serializable;

@Jpf.Controller(
    )
@Jpf.ViewProperties(
    value = {
        "<!-- This data is auto-generated. Hand-editing this section is not recommended. -->",
        "<view-properties>",
        "<pageflow-object id='pageflow:/b37374/Controller.jpf'/>",
        "<pageflow-object id='action:begin.do'>",
        "  <property value='80' name='x'/>",
        "  <property value='100' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='action:submitIt.do#b37374.Controller.TopForm'>",
        "  <property value='400' name='x'/>",
        "  <property value='100' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='action-call:@page:index.jsp@#@action:submitIt.do#b37374.Controller.TopForm@'>",
        "  <property value='276,320,320,364' name='elbowsX'/>",
        "  <property value='92,92,92,92' name='elbowsY'/>",
        "  <property value='East_1' name='fromPort'/>",
        "  <property value='West_1' name='toPort'/>",
        "</pageflow-object>",
        "<pageflow-object id='page:index.jsp'>",
        "  <property value='240' name='x'/>",
        "  <property value='100' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='page:results.jsp'>",
        "  <property value='60' name='x'/>",
        "  <property value='40' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='forward:path#success#index.jsp#@action:begin.do@'>",
        "  <property value='116,160,160,204' name='elbowsX'/>",
        "  <property value='92,92,92,92' name='elbowsY'/>",
        "  <property value='East_1' name='fromPort'/>",
        "  <property value='West_1' name='toPort'/>",
        "  <property value='success' name='label'/>",
        "</pageflow-object>",
        "<pageflow-object id='forward:path#success#results.jsp#@action:submitIt.do#b37374.Controller.TopForm@'>",
        "  <property value='364,230,230,96' name='elbowsX'/>",
        "  <property value='92,92,32,32' name='elbowsY'/>",
        "  <property value='West_1' name='fromPort'/>",
        "  <property value='East_1' name='toPort'/>",
        "  <property value='success' name='label'/>",
        "</pageflow-object>",
        "<pageflow-object id='formbeanprop:b37374.Controller.TopForm#detectedWebsites#b37374.Controller.Websites[]'/>",
        "<pageflow-object id='formbean:b37374.Controller.TopForm'/>",
        "</view-properties>"
    })
public class Controller extends PageFlowController
{


    // Uncomment this declaration to access Global.app.
    // 
    //     protected global.Global globalApp;
    // 

    // For an example of page flow exception handling see the example "catch" and "exception-handler"
    // annotations in {project}/WEB-INF/src/global/Global.app

    @Jpf.Action(
        forwards = {
            @Jpf.Forward(
                name = "success",
                path = "index.jsp") 
        })
    protected Forward begin()
    {
        TopForm tf = new TopForm();
        Websites[] ws = new Websites[3];
        tf.setDetectedWebsites(ws);
        
        for (int i=0;i<ws.length;i++) {
            // lets provide a set of null results
            if (i == 1)
                continue;
            ws[i] = new Websites();
            ws[i].setDomainOwner("results.jsp");
        }
        
        
        return new Forward( "success", tf);
    }

    @Jpf.Action(
        forwards = {
            @Jpf.Forward(
                name = "success",
                path = "results.jsp") 
        })
    protected Forward submitIt(TopForm form)
    {
        return new Forward("success");
    }

    /**
     * FormData get and set methods may be overwritten by the Form Bean editor.
     */
    public static class TopForm implements Serializable
    {
        private Websites[] detectedWebsites;


        public void setDetectedWebsites(Websites[] detectedWebsites)
        {
            this.detectedWebsites = detectedWebsites;
        }

        public Websites[] getDetectedWebsites()
        {
            return this.detectedWebsites;
        }
    }
    
    public static class Websites implements java.io.Serializable {
        private String _domainOwner;

        public String getDomainOwner() {return _domainOwner;}
        public void setDomainOwner(String domainOwner) {_domainOwner = domainOwner;}
    }
}
