<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Nested Flow
        </title>
    </head>
    <body>
        <h3> Nested Flow </h3>
            <netui:anchor action="returnToCurrentPage">return-to currentPage</netui:anchor>
            <br>
            <netui:anchor action="returnToCurrentPageOverrideInputs">return-to currentPage (override page inputs)</netui:anchor>
            <br>
            <netui:anchor action="returnToCurrentPageOverrideForm">return-to currentPage (override form)</netui:anchor>
            <br>
            <br>
            <netui:anchor action="returnToPreviousPage">return-to previousPage</netui:anchor>
            <br>
            <netui:anchor action="returnToPreviousPageOverrideForm">return-to previousPage (override form)</netui:anchor>
            <br>
            <netui:anchor action="returnToPreviousPageOverrideInputs">return-to previousPage (override page inputs)</netui:anchor>
            <br>
            <br>
            <netui:anchor action="returnToPage">return-to page</netui:anchor>
            <br>
            <netui:anchor action="returnToPageOverrideForm">return-to page (override form)</netui:anchor>
            <br>
            <netui:anchor action="returnToPageOverrideInputs">return-to page (override page inputs)</netui:anchor>  

    </body>
</netui:html>
