<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Page Flow Scoped Forms
        </title>
    </head>
    <body>
        <h3>Page Flow Scoped Forms</h3>
        
        <netui:anchor action="action1a">page flow scoped form -- initialized in page flow constructor</netui:anchor>
        <br>
        <netui:anchor action="action2a">page flow scoped form -- not initialized</netui:anchor>
        <br>
        <netui:anchor action="sessionScopeActionA">Struts session-scoped form</netui:anchor>
    </body>
</netui:html>
