<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<html>
    <body>
        <br/>

        <netui:form action="action1a">
            Current values:
            <table class="tablebody">
                <tr class="tablebody">
                    <td>Foo:</td>
                    <td>
                        <netui:span value="${actionForm.foo}"/>
                    </td>
                </tr>
                <tr class="tablebody">
                    <td>Bar:</td>
                    <td>
                        <netui:span value="${actionForm.bar}"/>
                    </td>
                </tr>
            </table>
            <br>
            <br>

            <table class="tablebody">
                <tr class="tablebody">
                    <td>Foo:</td>
                    <td>
                        <netui:textBox dataSource="actionForm.foo"/>
                    </td>
                </tr>
            </table>
            <br/>&nbsp;
            <netui:button value="Submit" type="submit"/>
        </netui:form>
        <br>
        <br>
        <netui:anchor href="begin.do">start over</netui:anchor>
    </body>
</html>
