<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Web Application Page
        </title>
    </head>
    <body>
        <netui:form action="postType">
            <table>
                <tr valign="top">
                    <td>Type:</td>
                    <td>
                    <netui:select dataSource="actionForm.type" defaultValue="${pageFlow.defaultType}" nullable="true" 
                        optionsDataSource="${pageFlow.types}"/>
                    </td>
                </tr>
            </table>
            <br/>&nbsp;
            <netui:button value="postType" type="submit"/>
        </netui:form><br>
        Form Two:
        <netui:form action="postType">
            <table>
                <tr valign="top">
                    <td>Type:</td>
                    <td>
                    <netui:select dataSource="actionForm.type" defaultValue="${pageFlow.defaultType}" nullable="true" 
                        optionsDataSource="${pageFlow.types}" nullableOptionText="[NULL]"/>
                    </td>
                </tr>
            </table>
            <br/>&nbsp;
            <netui:button value="postType" type="submit"/>
        </netui:form><br>
        Type: <netui:span value="${pageFlow.selectedType}"/> 
    </body>
</netui:html>
