<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Web Application Page
        </title>
    </head>
    <netui:body>
        
        <span id="<netui:rewriteName name="foo"/>" style="color:red">
            text inside a span
        </span>
        <br/>
        <img src="<netui:rewriteURL URL="/coreWeb/resources/images/bar-background.gif"/>"/><br />
        <img src="<netui:rewriteURL URL="../../resources/images/bar-background.gif"/>"/><br />
    </netui:body>
</netui:html>
