<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
    </head>
    <netui:body>
        <h4>Dump Request Paramaters</h4>
        <p style="color:green">
        This test submits a few values in a form to a result page.  The result page then sets up a value
        of the parameter names which is dumped to the screen using a repeater.
        </p>
        <netui:form action="submitForm" style="border: 1pt solid">
            <p>
            <input type="hidden" name="foo" value="bar">
            <input type="hidden" name="baz" value="blee">
            <netui:select dataSource="actionForm.select"  optionsDataSource="${pageFlow.selectOptions}" />
            <br>
            <netui:button value="Submit" type="submit" />
            </p>
        </netui:form><br>
    </netui:body>
</netui:html>
