/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * $Header:$
 */
// ------------------------------------------------------------------------------
//  Generated by WebLogic Workshop
// 
//  Created on: Fri Aug 29 14:13:22 GMT-07:00 2003
//  By: rfeit
// -----------------------------------------------------------------------------
package miniTests.multipartRequest;
import org.apache.beehive.netui.pageflow.Forward;
import org.apache.beehive.netui.pageflow.PageFlowController;
import org.apache.beehive.netui.pageflow.annotations.Jpf;
import org.apache.beehive.netui.pageflow.scoping.ScopedRequest;
import org.apache.struts.upload.FormFile;

import java.io.Serializable;

/**
 * @jpf:controller
 * @jpf:view-properties view-properties::
 * <!-- This data is auto-generated. Hand-editing this section is not recommended. -->
 * <view-properties>
 * <pageflow-object id="pageflow:/multipartRequest/multipartRequestController.jpf"/>
 * <pageflow-object id="action:begin.do">
 *   <property value="520" name="x"/>
 *   <property value="260" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="action:someAction.do#multipartRequest.multipartRequestController.SomeActionForm">
 *   <property value="480" name="x"/>
 *   <property value="400" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="action:nonFormAction.do">
 *   <property value="360" name="x"/>
 *   <property value="540" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="action:reset.do">
 *   <property value="200" name="x"/>
 *   <property value="60" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="action:someOtherAction.do">
 *   <property value="140" name="x"/>
 *   <property value="260" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="page:input.jsp">
 *   <property value="240" name="x"/>
 *   <property value="140" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="page:output.jsp">
 *   <property value="260" name="x"/>
 *   <property value="440" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="page:someOtherPage.jsp">
 *   <property value="140" name="x"/>
 *   <property value="360" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="forward:path#success#input.jsp#@action:begin.do@">
 *   <property value="484,380,380,276" name="elbowsX"/>
 *   <property value="252,252,132,132" name="elbowsY"/>
 *   <property value="West_1" name="fromPort"/>
 *   <property value="East_1" name="toPort"/>
 *   <property value="success" name="label"/>
 * </pageflow-object>
 * <pageflow-object id="forward:path#success#output.jsp#@action:someAction.do#multipartRequest.multipartRequestController.SomeActionForm@">
 *   <property value="444,370,370,296" name="elbowsX"/>
 *   <property value="392,392,432,432" name="elbowsY"/>
 *   <property value="West_1" name="fromPort"/>
 *   <property value="East_1" name="toPort"/>
 *   <property value="success" name="label"/>
 * </pageflow-object>
 * <pageflow-object id="forward:path#success#output.jsp#@action:nonFormAction.do@">
 *   <property value="324,310,310,296" name="elbowsX"/>
 *   <property value="532,532,443,443" name="elbowsY"/>
 *   <property value="West_1" name="fromPort"/>
 *   <property value="East_2" name="toPort"/>
 *   <property value="success" name="label"/>
 * </pageflow-object>
 * <pageflow-object id="forward:path#success#input.jsp#@action:reset.do@">
 *   <property value="200,200,202,204" name="elbowsX"/>
 *   <property value="104,132,132,132" name="elbowsY"/>
 *   <property value="South_1" name="fromPort"/>
 *   <property value="West_1" name="toPort"/>
 *   <property value="success" name="label"/>
 * </pageflow-object>
 * <pageflow-object id="forward:path#success#someOtherPage.jsp#@action:someOtherAction.do@">
 *   <property value="140,140,140,140" name="elbowsX"/>
 *   <property value="304,310,310,316" name="elbowsY"/>
 *   <property value="South_1" name="fromPort"/>
 *   <property value="North_1" name="toPort"/>
 *   <property value="success" name="label"/>
 * </pageflow-object>
 * <pageflow-object id="formbeanprop:multipartRequest.multipartRequestController.SomeActionForm#formProp#java.lang.String"/>
 * <pageflow-object id="formbeanprop:multipartRequest.multipartRequestController.SomeActionForm#formFile#org.apache.struts.upload.FormFile"/>
 * <pageflow-object id="formbean:multipartRequest.multipartRequestController.SomeActionForm"/>
 * <pageflow-object id="action-call:@page:input.jsp@#@action:someAction.do#multipartRequest.multipartRequestController.SomeActionForm@">
 *   <property value="276,360,360,444" name="elbowsX"/>
 *   <property value="132,132,392,392" name="elbowsY"/>
 *   <property value="East_1" name="fromPort"/>
 *   <property value="West_1" name="toPort"/>
 * </pageflow-object>
 * <pageflow-object id="action-call:@page:someOtherPage.jsp@#@action:begin.do@">
 *   <property value="176,330,330,484" name="elbowsX"/>
 *   <property value="352,352,252,252" name="elbowsY"/>
 *   <property value="East_1" name="fromPort"/>
 *   <property value="West_1" name="toPort"/>
 * </pageflow-object>
 * <pageflow-object id="action-call:@page:input.jsp@#@action:reset.do@">
 *   <property value="240,240,238,236" name="elbowsX"/>
 *   <property value="96,52,52,52" name="elbowsY"/>
 *   <property value="North_1" name="fromPort"/>
 *   <property value="East_1" name="toPort"/>
 * </pageflow-object>
 * <pageflow-object id="action-call:@page:output.jsp@#@action:someAction.do#multipartRequest.multipartRequestController.SomeActionForm@">
 *   <property value="296,370,370,444" name="elbowsX"/>
 *   <property value="432,432,392,392" name="elbowsY"/>
 *   <property value="East_1" name="fromPort"/>
 *   <property value="West_1" name="toPort"/>
 * </pageflow-object>
 * <pageflow-object id="action-call:@page:input.jsp@#@action:someOtherAction.do@">
 *   <property value="204,190,190,176" name="elbowsX"/>
 *   <property value="143,143,252,252" name="elbowsY"/>
 *   <property value="West_2" name="fromPort"/>
 *   <property value="East_1" name="toPort"/>
 * </pageflow-object>
 * <pageflow-object id="action-call:@page:output.jsp@#@action:begin.do@">
 *   <property value="296,390,390,484" name="elbowsX"/>
 *   <property value="432,432,263,263" name="elbowsY"/>
 *   <property value="East_1" name="fromPort"/>
 *   <property value="West_2" name="toPort"/>
 * </pageflow-object>
 * </view-properties>
 * ::
 */
@Jpf.Controller(
    )
@Jpf.ViewProperties(
    value = {
        "<!-- This data is auto-generated. Hand-editing this section is not recommended. -->",
        "<view-properties>",
        "<pageflow-object id='pageflow:/multipartRequest/multipartRequestController.jpf'/>",
        "<pageflow-object id='action:begin.do'>",
        "  <property value='520' name='x'/>",
        "  <property value='260' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='action:someAction.do#multipartRequest.multipartRequestController.SomeActionForm'>",
        "  <property value='480' name='x'/>",
        "  <property value='400' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='action:nonFormAction.do'>",
        "  <property value='360' name='x'/>",
        "  <property value='540' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='action:reset.do'>",
        "  <property value='200' name='x'/>",
        "  <property value='60' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='action:someOtherAction.do'>",
        "  <property value='140' name='x'/>",
        "  <property value='260' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='page:input.jsp'>",
        "  <property value='240' name='x'/>",
        "  <property value='140' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='page:output.jsp'>",
        "  <property value='260' name='x'/>",
        "  <property value='440' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='page:someOtherPage.jsp'>",
        "  <property value='140' name='x'/>",
        "  <property value='360' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='forward:path#success#input.jsp#@action:begin.do@'>",
        "  <property value='484,380,380,276' name='elbowsX'/>",
        "  <property value='252,252,132,132' name='elbowsY'/>",
        "  <property value='West_1' name='fromPort'/>",
        "  <property value='East_1' name='toPort'/>",
        "  <property value='success' name='label'/>",
        "</pageflow-object>",
        "<pageflow-object id='forward:path#success#output.jsp#@action:someAction.do#multipartRequest.multipartRequestController.SomeActionForm@'>",
        "  <property value='444,370,370,296' name='elbowsX'/>",
        "  <property value='392,392,432,432' name='elbowsY'/>",
        "  <property value='West_1' name='fromPort'/>",
        "  <property value='East_1' name='toPort'/>",
        "  <property value='success' name='label'/>",
        "</pageflow-object>",
        "<pageflow-object id='forward:path#success#output.jsp#@action:nonFormAction.do@'>",
        "  <property value='324,310,310,296' name='elbowsX'/>",
        "  <property value='532,532,443,443' name='elbowsY'/>",
        "  <property value='West_1' name='fromPort'/>",
        "  <property value='East_2' name='toPort'/>",
        "  <property value='success' name='label'/>",
        "</pageflow-object>",
        "<pageflow-object id='forward:path#success#input.jsp#@action:reset.do@'>",
        "  <property value='200,200,202,204' name='elbowsX'/>",
        "  <property value='104,132,132,132' name='elbowsY'/>",
        "  <property value='South_1' name='fromPort'/>",
        "  <property value='West_1' name='toPort'/>",
        "  <property value='success' name='label'/>",
        "</pageflow-object>",
        "<pageflow-object id='forward:path#success#someOtherPage.jsp#@action:someOtherAction.do@'>",
        "  <property value='140,140,140,140' name='elbowsX'/>",
        "  <property value='304,310,310,316' name='elbowsY'/>",
        "  <property value='South_1' name='fromPort'/>",
        "  <property value='North_1' name='toPort'/>",
        "  <property value='success' name='label'/>",
        "</pageflow-object>",
        "<pageflow-object id='formbeanprop:multipartRequest.multipartRequestController.SomeActionForm#formProp#java.lang.String'/>",
        "<pageflow-object id='formbeanprop:multipartRequest.multipartRequestController.SomeActionForm#formFile#org.apache.struts.upload.FormFile'/>",
        "<pageflow-object id='formbean:multipartRequest.multipartRequestController.SomeActionForm'/>",
        "<pageflow-object id='action-call:@page:input.jsp@#@action:someAction.do#multipartRequest.multipartRequestController.SomeActionForm@'>",
        "  <property value='276,360,360,444' name='elbowsX'/>",
        "  <property value='132,132,392,392' name='elbowsY'/>",
        "  <property value='East_1' name='fromPort'/>",
        "  <property value='West_1' name='toPort'/>",
        "</pageflow-object>",
        "<pageflow-object id='action-call:@page:someOtherPage.jsp@#@action:begin.do@'>",
        "  <property value='176,330,330,484' name='elbowsX'/>",
        "  <property value='352,352,252,252' name='elbowsY'/>",
        "  <property value='East_1' name='fromPort'/>",
        "  <property value='West_1' name='toPort'/>",
        "</pageflow-object>",
        "<pageflow-object id='action-call:@page:input.jsp@#@action:reset.do@'>",
        "  <property value='240,240,238,236' name='elbowsX'/>",
        "  <property value='96,52,52,52' name='elbowsY'/>",
        "  <property value='North_1' name='fromPort'/>",
        "  <property value='East_1' name='toPort'/>",
        "</pageflow-object>",
        "<pageflow-object id='action-call:@page:output.jsp@#@action:someAction.do#multipartRequest.multipartRequestController.SomeActionForm@'>",
        "  <property value='296,370,370,444' name='elbowsX'/>",
        "  <property value='432,432,392,392' name='elbowsY'/>",
        "  <property value='East_1' name='fromPort'/>",
        "  <property value='West_1' name='toPort'/>",
        "</pageflow-object>",
        "<pageflow-object id='action-call:@page:input.jsp@#@action:someOtherAction.do@'>",
        "  <property value='204,190,190,176' name='elbowsX'/>",
        "  <property value='143,143,252,252' name='elbowsY'/>",
        "  <property value='West_2' name='fromPort'/>",
        "  <property value='East_1' name='toPort'/>",
        "</pageflow-object>",
        "<pageflow-object id='action-call:@page:output.jsp@#@action:begin.do@'>",
        "  <property value='296,390,390,484' name='elbowsX'/>",
        "  <property value='432,432,263,263' name='elbowsY'/>",
        "  <property value='East_1' name='fromPort'/>",
        "  <property value='West_2' name='toPort'/>",
        "</pageflow-object>",
        "</view-properties>"
    })
public class multipartRequestController extends PageFlowController
{
    public String pfProp;
    public FormFile pfFile;


    /**
     * This method represents the point of entry into the pageflow
     * @jpf:action
     * @jpf:forward name="success" path="input.jsp"
     */
    @Jpf.Action(
        forwards = {
            @Jpf.Forward(
                name = "success",
                path = "input.jsp") 
        })
    protected Forward begin()
    {
        return new Forward( "success" );
    }

    /**
     * @jpf:action
     * @jpf:forward name="success" path="output.jsp"
     */
    @Jpf.Action(
        forwards = {
            @Jpf.Forward(
                name = "success",
                path = "output.jsp") 
        })
    protected Forward someAction(SomeActionForm form)
    {
        return new Forward("success", form);
    }

    /**
     * @jpf:action
     * @jpf:forward name="success" path="output.jsp"
     */
    @Jpf.Action(
        forwards = {
            @Jpf.Forward(
                name = "success",
                path = "output.jsp") 
        })
    protected Forward nonFormAction()
    {
        return new Forward("success", new SomeActionForm());
    }

    /**
     * @jpf:action
     * @jpf:forward name="success" path="input.jsp"
     */
    @Jpf.Action(
        forwards = {
            @Jpf.Forward(
                name = "success",
                path = "input.jsp") 
        })
    protected Forward reset()
    {
        pfFile = null;
        pfProp = null;
        return new Forward("success");
    }

    /**
     * @jpf:action
     * @jpf:forward name="success" path="someOtherPage.jsp"
     */
    @Jpf.Action(
        forwards = {
            @Jpf.Forward(
                name = "success",
                path = "someOtherPage.jsp") 
        })
    protected Forward someOtherAction()
    {
        return new Forward("success");
    }

    /**
     * FormData get and set methods may be overwritten by the Form Bean editor.
     */
    public static class SomeActionForm implements Serializable
    {
        private String formProp;

        private FormFile formFile;

        public void setFormProp(String formProp)
        {
            this.formProp = formProp;
        }

        public String getFormProp()
        {
            return this.formProp;
        }

        public void setFormFile(FormFile formFile)
        {
            this.formFile = formFile;
        }

        public FormFile getFormFile()
        {
            return this.formFile;
        }
        
        public String getFileContents()
            throws Exception
        {
            return formFile != null ? new String( formFile.getFileData() ) : "";
        } 
    }
    
    public boolean getScoped()
    {
        return getRequest() instanceof ScopedRequest;
    }
    
    public String getFileContents()
        throws Exception
    {
        return pfFile != null ? new String( pfFile.getFileData() ) : "";
    } 

}
