<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Label Default Values
        </title>
    </head>
    <netui:body>
    <h4>Label Default Values</h4>
    <p style="color:green">
    This test has a set of labels which bind to an object that has a value of null.  In each case we will then bind
    to the default value, if it exists.  When nothing at all is found, the empty string is output.  This happens
    in the first an last test of each group.  The first doesn't specify a defaultValue.  The last maps to a defaultValue
    value bound to null.  The middle two, bind to a literal in the tag and a value in the page flow.
    </p>
    <hr>
    <table cellspacing="0" border="1" cellpadding="3">

    <tr><td>Null Object/No Default</td><td><netui:span value="${pageFlow.nullValue}" /></td></tr>
    <tr><td>Null Object/Default</td><td><netui:span defaultValue="[NULL]" value="${pageFlow.nullValue}" /></td></tr>
    <tr><td>Null Object/Bound Default</td><td><netui:span defaultValue="${pageFlow.defaultBound}" value="${pageFlow.nullValue}" /></td></tr>
    <tr><td>Null Object/Bound Null Default</td><td><netui:span defaultValue="${pageFlow.nullValue}" value="${pageFlow.nullValue}" /></td></tr>

    <tr><td>Null Object, Date Formatter/No Default</td><td><netui:span value="${pageFlow.nullValue}"><netui:formatDate pattern="MM/dd/yyyy"/></netui:span></td></tr>
    <tr><td>Null Object, Date Formatter/Default</td><td><netui:span value="${pageFlow.nullValue}" formatDefaultValue="true" defaultValue="[NULL]"><netui:formatDate pattern="MM/dd/yyyy"/></netui:span></td></tr>
    <tr><td>Null Object, Date Formatter/Bound Default</td><td><netui:span value="${pageFlow.nullValue}" formatDefaultValue="true" defaultValue="${pageFlow.defaultDate}"><netui:formatDate pattern="MM/dd/yyyy"/></netui:span></td></tr>
    <tr><td>Null Object, Date Formatter/Bound Null Default</td><td><netui:span formatDefaultValue="true" value="${pageFlow.nullValue}" defaultValue="${pageFlow.nullValue}"><netui:formatDate pattern="MM/dd/yyyy"/></netui:span></td></tr>
    </table>
    </netui:body>
</netui:html>
