/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * $Header:$
 */
// ------------------------------------------------------------------------------
//  Generated by WebLogic Workshop
// 
//  Created on: Sun Jul 27 10:22:46 GMT-07:00 2003
//  By: rfeit
// -----------------------------------------------------------------------------
package miniTests.upload;
import org.apache.beehive.netui.pageflow.Forward;
import org.apache.beehive.netui.pageflow.PageFlowController;
import org.apache.beehive.netui.pageflow.annotations.Jpf;
import org.apache.beehive.netui.pageflow.scoping.ScopedRequest;
import org.apache.struts.upload.FormFile;

import java.io.Serializable;

/**
 * @jpf:controller
 * @jpf:view-properties view-properties::
 * <!-- This data is auto-generated. Hand-editing this section is not recommended. -->
 * <view-properties>
 * <pageflow-object id="pageflow:/upload/uploadController.jpf"/>
 * <pageflow-object id="action:begin.do">
 *   <property value="80" name="x"/>
 *   <property value="100" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="page:index.jsp">
 *   <property value="240" name="x"/>
 *   <property value="100" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="forward:path#success#index.jsp#@action:begin.do@">
 *   <property value="116,160,160,204" name="elbowsX"/>
 *   <property value="92,92,92,92" name="elbowsY"/>
 *   <property value="East_1" name="fromPort"/>
 *   <property value="West_1" name="toPort"/>
 *   <property value="success" name="label"/>
 * </pageflow-object>
 * <pageflow-object id="action:upload.do#upload.uploadController.UploadForm">
 *   <property value="240" name="x"/>
 *   <property value="220" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="action-call:@page:index.jsp@#@action:upload.do#upload.uploadController.UploadForm@">
 *   <property value="240,240,240,240" name="elbowsX"/>
 *   <property value="144,160,160,176" name="elbowsY"/>
 *   <property value="South_1" name="fromPort"/>
 *   <property value="North_1" name="toPort"/>
 * </pageflow-object>
 * <pageflow-object id="formbeanprop:upload.uploadController.UploadForm#file#org.apache.struts.upload.FormFile"/>
 * <pageflow-object id="formbean:upload.uploadController.UploadForm"/>
 * <pageflow-object id="formbeanprop:upload.uploadController.UploadForm#label#java.lang.String"/>
 * <pageflow-object id="page:results.jsp">
 *   <property value="240" name="x"/>
 *   <property value="340" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="forward:path#success#results.jsp#@action:upload.do#upload.uploadController.UploadForm@">
 *   <property value="240,240,240,240" name="elbowsX"/>
 *   <property value="264,280,280,296" name="elbowsY"/>
 *   <property value="South_1" name="fromPort"/>
 *   <property value="North_1" name="toPort"/>
 *   <property value="success" name="label"/>
 * </pageflow-object>
 * <pageflow-object id="action-call:@page:results.jsp@#@action:begin.do@">
 *   <property value="204,160,160,116" name="elbowsX"/>
 *   <property value="332,332,103,103" name="elbowsY"/>
 *   <property value="West_1" name="fromPort"/>
 *   <property value="East_2" name="toPort"/>
 * </pageflow-object>
 * </view-properties>
 * ::
 */
@Jpf.Controller(
    )
@Jpf.ViewProperties(
    value = {
        "<!-- This data is auto-generated. Hand-editing this section is not recommended. -->",
        "<view-properties>",
        "<pageflow-object id='pageflow:/upload/uploadController.jpf'/>",
        "<pageflow-object id='action:begin.do'>",
        "  <property value='80' name='x'/>",
        "  <property value='100' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='page:index.jsp'>",
        "  <property value='240' name='x'/>",
        "  <property value='100' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='forward:path#success#index.jsp#@action:begin.do@'>",
        "  <property value='116,160,160,204' name='elbowsX'/>",
        "  <property value='92,92,92,92' name='elbowsY'/>",
        "  <property value='East_1' name='fromPort'/>",
        "  <property value='West_1' name='toPort'/>",
        "  <property value='success' name='label'/>",
        "</pageflow-object>",
        "<pageflow-object id='action:upload.do#upload.uploadController.UploadForm'>",
        "  <property value='240' name='x'/>",
        "  <property value='220' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='action-call:@page:index.jsp@#@action:upload.do#upload.uploadController.UploadForm@'>",
        "  <property value='240,240,240,240' name='elbowsX'/>",
        "  <property value='144,160,160,176' name='elbowsY'/>",
        "  <property value='South_1' name='fromPort'/>",
        "  <property value='North_1' name='toPort'/>",
        "</pageflow-object>",
        "<pageflow-object id='formbeanprop:upload.uploadController.UploadForm#file#org.apache.struts.upload.FormFile'/>",
        "<pageflow-object id='formbean:upload.uploadController.UploadForm'/>",
        "<pageflow-object id='formbeanprop:upload.uploadController.UploadForm#label#java.lang.String'/>",
        "<pageflow-object id='page:results.jsp'>",
        "  <property value='240' name='x'/>",
        "  <property value='340' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='forward:path#success#results.jsp#@action:upload.do#upload.uploadController.UploadForm@'>",
        "  <property value='240,240,240,240' name='elbowsX'/>",
        "  <property value='264,280,280,296' name='elbowsY'/>",
        "  <property value='South_1' name='fromPort'/>",
        "  <property value='North_1' name='toPort'/>",
        "  <property value='success' name='label'/>",
        "</pageflow-object>",
        "<pageflow-object id='action-call:@page:results.jsp@#@action:begin.do@'>",
        "  <property value='204,160,160,116' name='elbowsX'/>",
        "  <property value='332,332,103,103' name='elbowsY'/>",
        "  <property value='West_1' name='fromPort'/>",
        "  <property value='East_2' name='toPort'/>",
        "</pageflow-object>",
        "</view-properties>"
    })
public class uploadController extends PageFlowController
{
    /**
     * @jpf:action
     * @jpf:forward name="success" path="index.jsp"
     */
    @Jpf.Action(
        forwards = {
            @Jpf.Forward(
                name = "success",
                path = "index.jsp") 
        })
    protected Forward begin()
    {
        return new Forward( "success" );
    }

    /**
     * @jpf:action
     * @jpf:forward name="success" path="results.jsp"
     */
    @Jpf.Action(
        forwards = {
            @Jpf.Forward(
                name = "success",
                path = "results.jsp") 
        })
    protected Forward upload( UploadForm form )
        throws Exception
    {
        return new Forward( "success", "init", form );
    }
    
    public boolean getScoped()
    {
        return getRequest() instanceof ScopedRequest;
    }

    /**
     * FormData get and set methods may be overwritten by the Form Bean editor.
     */
    public static class UploadForm implements Serializable
    {
        private String _label;
        private FormFile _file;


        public void setLabel( String label )
        {
            _label = label;
        }

        public String getLabel()
        {
            return _label;
        }

        public void setFile( FormFile file )
        {
            _file = file;
        }

        public FormFile getFile()
        {
            return _file;
        }
        
        public String getFileDataString()
            throws Exception
        {
            return new String( _file.getFileData() );
        }
    }
}
