<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <netui:body>
        <br/>
        <netui:form action="submitForm2">
            <table class="tablebody">
                <tr class="tablebody">
                    <td>Text Box:</td>
                    <td>
                        <netui:textBox dataSource="actionForm.textBox" maxlength="${pageFlow.nullBinding}" size="${pageFlow.nullBinding}"/>
                    </td>
                </tr>
                <tr class="tablebody">
                    <td>Text Area:</td>
                    <td>
                        <netui:textArea dataSource="actionForm.textArea" cols="${pageFlow.nullBinding}" rows="${pageFlow.nullBinding}"/>
                    </td>
                </tr>
                <tr class="tablebody">
                    <td>Select:</td>
                    <td>
                        <netui:select dataSource="actionForm.select" size="${pageFlow.nullBinding}">
                        <netui:selectOption value="Option One"/>
                        <netui:selectOption value="Option Two"/>
                        <netui:selectOption value="Option Three"/>
                        <netui:selectOption value="Option Four"/>
                        <netui:selectOption value="Option Five"/>
                        </netui:select>
                    </td>
                </tr>
            </table>
            <br/>&nbsp;
            <netui:button value="Submit" type="submit"/>
        </netui:form>
    </netui:body>
</netui:html>
