<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <body>
        <br/>
        <netui:form action="submitForm">
            <table class="tablebody">
                <tr class="tablebody">
                    <td>Text Box:</td>
                    <td>
                        <netui:textBox dataSource="actionForm.textBox" maxlength="${pageFlow.tbMaxLength}" size="${pageFlow.tbSize}"/>
                    </td>
                </tr>
                <tr class="tablebody">
                    <td>Text Area:</td>
                    <td>
                        <netui:textArea dataSource="actionForm.textArea" cols="${pageFlow.taCols}" rows="${pageFlow.taRows}"/>
                    </td>
                </tr>
                <tr class="tablebody">
                    <td>Select:</td>
                    <td>
                        <netui:select dataSource="actionForm.select" size="${pageFlow.selectSize}">
                        <netui:selectOption tagId="Option-1" value="Option One"/>
                        <netui:selectOption tagId="Option-2" value="Option Two"/>
                        <netui:selectOption tagId="Option-3" value="Option Three"/>
                        <netui:selectOption tagId="Option-4" value="Option Four"/>
                        <netui:selectOption tagId="Option-5" value="Option Five"/> 
                        </netui:select>
                    </td>
                </tr>
            </table>
            <br/>&nbsp;
            <netui:button value="Submit" type="submit"/>
        </netui:form>
    </body>
</netui:html>
