<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Web Application Page
        </title>
    </head>
    <netui:body>
    <netui:anchor action="goForm">Form Stuff</netui:anchor>
    <hr />
    <netui:image width="${pageFlow.nullBinding}"
        src="/coreWeb/index/Beehive.gif"
        alt="${pageFlow.nullBinding}"
        height="${pageFlow.nullBinding}"
        hspace="${pageFlow.nullBinding}"
        vspace="${pageFlow.nullBinding}" />
    <br />
    <netui:imageAnchor
        action="begin"
        border="${pageFlow.nullBinding}"
        width="${pageFlow.nullBinding}"
        src="/coreWeb/index/Beehive.gif"
        alt="${pageFlow.nullBinding}"
        height="${pageFlow.nullBinding}"
        hspace="${pageFlow.nullBinding}"
        vspace="${pageFlow.nullBinding}" />
    </netui:body>
</netui:html>
