<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            handled bothHave
        </title>
    </head>
    <body>
        handled bothHave
        <br>
        <font color="blue"><netui:span value="${requestScope.note}"/></font>
        <br>
        <netui:anchor action="begin">start over</netui:anchor>
    </body>
</netui:html>
