<!--Generated by Weblogic Workshop-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>

<html>
  <head>
    <netui:base />
    <title><netui-template:attribute name="title"/></title>
    <link href="<%=request.getContextPath()%>/resources/css/style.css" type="text/css" rel="stylesheet"/>
  </head>
  <body style="margin:0">
    <jsp:include page="/resources/jsp/header.jsp" />
    <br/>
    <netui-template:includeSection name="bodySection"></netui-template:includeSection>
  </body>
</html>
