<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Web Application Page
        </title>
    </head>
    <body>
        <netui-data:callPageFlow method="callableMethod" resultId="call1"><netui-data:methodParameter type="java.lang.String" value="String"></netui-data:methodParameter></netui-data:callPageFlow>
        <netui:span value="${pageScope.call1}"></netui:span> <br><netui-data:callPageFlow method="callableMethod" resultId="call2"><netui-data:methodParameter type="int" value="2"></netui-data:methodParameter></netui-data:callPageFlow>
        <netui:span value="${pageScope.call2}"></netui:span>
    </body>
</netui:html>
