<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Web Application Page
        </title>
    </head>
    <netui:body>
        <p>
            <netui:form action="submit" focus="firstName">
                <table class="tablebody">
                    <tr class="tablehead">
                        <td>LastName:</td>
                        <td>
                        <netui:textBox dataSource="actionForm.lastName" tagId="lastName"></netui:textBox>
                        </td>
                    </tr>
                    <tr class="tablehead">
                        <td>FirstName:</td>
                        <td>
                        <netui:textBox dataSource="actionForm.firstName" tagId="firstName"></netui:textBox>
                        </td>
                    </tr>
                </table>
                <br/>
                <netui:anchor formSubmit="true" action="${pageFlow.action}">Submit pageFlow.action("Foo")
                    <netui:parameter name="anchorForm" value='Submit pageFlow.action("Foo")'></netui:parameter>
                </netui:anchor>
                &nbsp;
                <netui:anchor formSubmit="true" action="baz">Submit Baz
                    <netui:parameter name="anchorForm" value='Submit Baz'></netui:parameter>
                </netui:anchor>
                &nbsp;
                <netui:anchor formSubmit="true">Default Form Submit
                    <netui:parameter name="anchorForm" value='Default Form Submit'></netui:parameter>
                </netui:anchor>
                
                <netui:imageAnchor action="imageSubmit" src="./../../resources/images/bar-background.gif" formSubmit="true">
                    <netui:parameter name="anchorForm" value="Submit from ImageAnchor"></netui:parameter>
                </netui:imageAnchor>
            &nbsp;
            <netui:imageButton src="../../images/godzilla.gif" rolloverImage="../../images/godzillaRollover.gif"/>
            </netui:form><br/>
        <netui:imageAnchor action="begin" src="../../images/godzilla.gif" rolloverImage="../../images/godzillaRollover.gif" height="100" width="80">PostBack</netui:imageAnchor>
    </netui:body>
</netui:html>
