<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib prefix="netui" uri="http://beehive.apache.org/netui/tags-html-1.0"%>
<netui:html idScope="foo">
<head>
</head>
<body>
Verify that the div is not generated by the netui HTML tag.
</body>
</netui:html>
