<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Web Application Page
        </title>
    </head>
    <netui:body>
        <netui:form action="postForm" tagId="form">
            <table class="tablebody">
                <tr class="tablehead">
                    <td>LastName:</td>
                    <td>
                    <netui:textBox dataSource="actionForm.lastName" tagId="lastName"></netui:textBox>
                    </td>
                </tr>
                <tr class="tablehead">
                    <td>FirstName:</td>
                    <td>
                    <netui:textBox dataSource="actionForm.firstName" tagId="firstName"></netui:textBox>
                    </td>
                </tr>
                <tr>
                    <td>Type:</td>
                    <td>
                    &nbsp;
                    <netui:select dataSource="actionForm.type" tagId="select">
                        <netui:selectOption value="Select Option One" tagId="opt1"/>
                        <netui:selectOption value="Select Option Two" tagId="opt2"/>
                        <netui:selectOption value="Select Option Three" tagId="opt3"/>
                    </netui:select>
                    </td>
                </tr>
            </table>
            <br/>&nbsp;
            <netui:button value="postForm" type="submit" tagId="submit"></netui:button>&nbsp;
            <netui:imageButton src="./../../resources/images/folder_16_pad.gif" tagId="imageButton"></netui:imageButton>
        </netui:form>
        <hr />
        <netui:span value="${pageFlow.action}" tagId="label"/> <br>
        <netui:anchor action="begin" tagId="anchor">Home</netui:anchor><br>
        <netui:imageAnchor action="begin" src="./../../resources/images/folder_16_pad.gif" tagId="imageAnchor"></netui:imageAnchor><br>
        <netui:image src="./../../resources/images/bar-background.gif" tagId="image"></netui:image>
    </netui:body>
</netui:html>
