<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<html>
    <head>
        <title>
            <netui-template:attribute name="title" defaultValue="Unknown Page"></netui-template:attribute>
        </title>
    </head>
    <body>
        <h4>
            <netui-template:attribute name="title" defaultValue="Unknown Page"></netui-template:attribute>
        </h4>
        <netui-template:includeSection name="content" defaultPage="../defaultContent.jsp">
        </netui-template:includeSection>
    </body>
</html>
