<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Web Application Page
        </title>
    </head>
    <netui:body>
        <netui:anchor action="begin">
            Postback
            <netui:parameter name="name" value="value"></netui:parameter>
            <netui:parameter name="name" value="value"></netui:parameter>
        </netui:anchor>
        <netui:form action="postForm">
            <table class="tablebody">
                <tr class="tablehead">
                    <td>Name:</td>
                    <td>
                    <netui:textBox dataSource="actionForm.name"></netui:textBox>
                    </td>
                </tr>
            </table>
            <br/>
            &nbsp;
            <netui:anchor formSubmit="true">
                Submit
                <netui:parameter name="name" value="value"></netui:parameter>
                <netui:parameter name="name" value="value"></netui:parameter>
                
            </netui:anchor>
            
        </netui:form>
    </netui:body>
</netui:html>
