<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <body>
        <h4>Disabled Bound to PageFlow</h4>
        <p style="color:green">
        This test is the same as the <b>Disable</b> test except that the value of the <b>disabled</b> attribute
        is bound to a page flow variable.  In this case all of the various form items are disabled.  When the
        form is posted a results page displays the contents of the form posted.  When you return from the
        results page the form will become enabled (disabled="false").
        </p>
        <br>
        <netui:form action="submitForm">
            <table class="tablebody">
                <tr class="tablebody">
                    <td>Text Box:</td>
                    <td>
                        <netui:textBox dataSource="actionForm.textBox"
                                defaultValue="Default Value" disabled="${pageFlow.disableBinding}" />
                    </td>
                </tr>
                <tr class="tablebody">
                    <td>Text Area:</td>
                    <td>
                        <netui:textArea dataSource="actionForm.textArea"
                                defaultValue="Default Value" disabled="${pageFlow.disableBinding}" />
                    </td>
                </tr>
                <tr class="tablebody">
                    <td>Select/Options</td>
                    <td>
                        <netui:select dataSource="actionForm.select" disabled="${pageFlow.disableBinding}" defaultValue="Option Two">
                        <netui:selectOption value="Option One"/>
                        <netui:selectOption value="Option Two"/>
                        <netui:selectOption value="Option Three"/>
                        <netui:selectOption value="Option Four"/>
                        <netui:selectOption value="Option Five"/>
                        </netui:select>
                    </td>
                </tr>
                <tr class="tablebody">
                    <td>Select/Options Source</td>
                    <td>
                        <netui:select dataSource="actionForm.selectThree"
                                optionsDataSource="${pageFlow.selectOptions}"
                                defaultValue="Option 3"
                                disabled="${pageFlow.disableBinding}" />
                    </td>
                </tr>
                <tr class="tablebody">
                    <td>Select (option Disabled):</td>
                    <td>
                        <netui:select dataSource="actionForm.selectTwo"
                                defaultValue="Option Nine">
                        <netui:selectOption value="Option Six"
                                disabled="${pageFlow.disableBinding}"/>
                        <netui:selectOption value="Option Seven"/>
                        <netui:selectOption value="Option Eight"
                                disabled="${pageFlow.disableBinding}"/>
                        <netui:selectOption value="Option Nine"/>
                        <netui:selectOption value="Option Ten"
                                disabled="${pageFlow.disableBinding}"/>
                        </netui:select>
                    </td>
                </tr>
                <tr class="tablebody">
                    <td>Radio Group/Options</td>
                    <td>
                        <netui:radioButtonGroup
                                dataSource="actionForm.radioGroup"
                                defaultValue="Radio Two"
                                disabled="${pageFlow.disableBinding}"
                        >
                           <netui:radioButtonOption value="Radio One"/><br />
                           <netui:radioButtonOption value="Radio Two"/><br />
                           <netui:radioButtonOption value="Radio Three"/><br />
                           <netui:radioButtonOption value="Radio Four"/><br />
                        </netui:radioButtonGroup>
                    </td>
                </tr>
                <tr class="tablebody">
                    <td>Radio Group/Options Source</td>
                    <td>
                        <netui:radioButtonGroup
                                dataSource="actionForm.radioGroup2"
                                defaultValue="Radio 2"
                                optionsDataSource="${pageFlow.radioOptions}"
                                disabled="${pageFlow.disableBinding}"
                        />
                    </td>
                </tr>
                <tr class="tablebody">
                    <td>CheckBox</td>
                    <td>
                        Check One <netui:checkBox
                                dataSource="actionForm.check1"
                                disabled="${pageFlow.disableBinding}"
                        /><br />
                        Check Two <netui:checkBox
                                dataSource="actionForm.check2"
                                disabled="${pageFlow.disableBinding}"
                        />
                    </td>
                </tr>
                <tr class="tablebody">
                    <td>CheckBox Group/Options Source</td>
                    <td>
                        <netui:checkBoxGroup
                                dataSource="actionForm.checkOne"
                                defaultValue="Check 3"
                                optionsDataSource="${pageFlow.checkOptions}"
                                disabled="${pageFlow.disableBinding}"
                        />
                    </td>
                </tr>
                <tr class="tablebody">
                    <td>CheckBox Group/Options</td>
                    <td>
                        <netui:checkBoxGroup
                                dataSource="actionForm.checkTwo"
                                defaultValue="Check Four"
                                disabled="${pageFlow.disableBinding}"
                        >
                           <netui:checkBoxOption value="Check One"/><br />
                           <netui:checkBoxOption value="Check Two"/><br />
                           <netui:checkBoxOption value="Check Three"/><br />
                           <netui:checkBoxOption value="Check Four"/><br />
                        </netui:checkBoxGroup>

                    </td>
                </tr>

            </table>
            <br>&nbsp;
            <netui:button value="Submit" type="submit"/>
            <netui:button value="Submit (Disabled)" type="submit"
                disabled="${pageFlow.disableBinding}"/>
        </netui:form>
    </body>
</netui:html>
