<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
  <head>
    <title>Web Application Page</title>
  </head>
  <body>
        <netui:form action="postback" focus="">
            <netui:parameter name="name" value="Form One"/>
            <netui:parameter name="foo" value="bar"/>
            <netui:parameter name="foo" value="baz"/>
            <netui:parameter name="foo" value="${pageFlow.listValues}"/>
            <netui:parameter name="foo" value="${pageFlow.stringValues}"/>
            <netui:parameter name="foo" value="${pageFlow.intValues}"/>
            <netui:button>Form One</netui:button>
        </netui:form>
        <netui:anchor action="link">Anchor One
            <netui:parameter name="name" value="Anchor"/>
            <netui:parameter name="foo" value="bar"/>
            <netui:parameter name="foo" value="baz"/>
            <netui:parameter name="foo" value="${pageFlow.listValues}"/>
            <netui:parameter name="foo" value="${pageFlow.stringValues}"/>
            <netui:parameter name="foo" value="${pageFlow.intValues}"/>
        </netui:anchor><br />
        <netui:anchor action="link">Null List/Null Strings
            <netui:parameter name="name" value="Null List/Null Strings"/>
            <netui:parameter name="foo" value="${pageFlow.nullList}"/>
            <netui:parameter name="foo" value="${pageFlow.nullString}"/>
        </netui:anchor><br />
        <netui:anchor action="link">Empty List/Empty Strings
            <netui:parameter name="name" value="Empty List/Empty Strings"/>
            <netui:parameter name="foo" value="${pageFlow.emptyList}"/>
            <netui:parameter name="foo" value="${pageFlow.emptyString}"/>
        </netui:anchor><br />
        <netui:anchor action="link">Single Param
            <netui:parameter name="name" value="Single Param"/>
            <netui:parameter name="foo" value="value"/>
        </netui:anchor><br />
        <netui:anchor action="link">Null Param
            <netui:parameter name="name" value="Null Param"/>
            <netui:parameter name="foo" value="${pageFlow.nullValue}"/>
        </netui:anchor><br />
        <netui:anchor action="link">Just List
            <netui:parameter name="name" value="Just List"/>
            <netui:parameter name="foo" value="${pageFlow.listValues}"/>
        </netui:anchor><br />
        <netui:anchor action="link">Just String
            <netui:parameter name="name" value="Just String"/>
            <netui:parameter name="foo" value="${pageFlow.stringValues}"/>
        </netui:anchor><br />
        <netui:anchor action="link">Int Values
            <netui:parameter name="name" value="Int Values"/>
            <netui:parameter name="foo" value="${pageFlow.intValues}"/>
        </netui:anchor><br />
        <netui:anchor action="link">Single String Array
            <netui:parameter name="name" value="Single String Array"/>
            <netui:parameter name="foo" value="${pageFlow.singleStringValue}"/>
        </netui:anchor><br />
        <netui:anchor action="link">Single List 
            <netui:parameter name="name" value="Single List"/>
            <netui:parameter name="foo" value="${pageFlow.singleListValue}"/>
        </netui:anchor><br />
  </body>
</netui:html>
