<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <body>
      <h4>List</h4>
      <netui-data:repeater dataSource="pageFlow.list">
      <netui-data:repeaterHeader><ul></netui-data:repeaterHeader>
      <netui-data:repeaterItem><li><netui:span value="${container.item}"/></li>
        </netui-data:repeaterItem>
      <netui-data:repeaterFooter></ul></netui-data:repeaterFooter>
      </netui-data:repeater>
      <hr />
      <h4>Enumeration</h4>
      <netui-data:repeater dataSource="pageFlow.e">
      <netui-data:repeaterHeader><ul></netui-data:repeaterHeader>
      <netui-data:repeaterItem><li><netui:span value="${container.item}"/></li>
        </netui-data:repeaterItem>
      <netui-data:repeaterFooter></ul></netui-data:repeaterFooter>
      </netui-data:repeater>
    </body>
</netui:html>
