/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * $Header:$
 */
// ------------------------------------------------------------------------------
//  Generated by WebLogic Workshop
// 
//  Created on: Tue Sep 02 09:29:14 MDT 2003
//  By: dolander
// -----------------------------------------------------------------------------
package tags.hidden;
import org.apache.beehive.netui.pageflow.Forward;
import org.apache.beehive.netui.pageflow.PageFlowController;
import org.apache.beehive.netui.pageflow.annotations.Jpf;

import java.io.Serializable;


@Jpf.Controller(
    )
@Jpf.ViewProperties(
    value = {
        "<!-- This data is auto-generated. Hand-editing this section is not recommended. -->",
        "<view-properties>",
        "<pageflow-object id='pageflow:/hidden/Controller.jpf'/>",
        "<pageflow-object id='page:index.jsp'>",
        "  <property value='240' name='x'/>",
        "  <property value='100' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='formbean:hidden.Controller.HiddenForm'/>",
        "<pageflow-object id='formbeanprop:hidden.Controller.HiddenForm#hidden#java.lang.String'/>",
        "<pageflow-object id='action:post.do#hidden.Controller.HiddenForm'>",
        "  <property value='360' name='x'/>",
        "  <property value='100' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='action-call:@page:index.jsp@#@action:post.do#hidden.Controller.HiddenForm@'>",
        "  <property value='276,300,300,324' name='elbowsX'/>",
        "  <property value='92,92,92,92' name='elbowsY'/>",
        "  <property value='East_1' name='fromPort'/>",
        "  <property value='West_1' name='toPort'/>",
        "</pageflow-object>",
        "<pageflow-object id='forward:path#success#index.jsp#@action:post.do#hidden.Controller.HiddenForm@'>",
        "  <property value='396,396,323,251' name='elbowsX'/>",
        "  <property value='92,56,56,56' name='elbowsY'/>",
        "  <property value='East_1' name='fromPort'/>",
        "  <property value='North_2' name='toPort'/>",
        "  <property value='success' name='label'/>",
        "</pageflow-object>",
        "<pageflow-object id='action:begin.do'>",
        "  <property value='80' name='x'/>",
        "  <property value='100' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='forward:path#success#index.jsp#@action:begin.do@'>",
        "  <property value='116,160,160,204' name='elbowsX'/>",
        "  <property value='92,92,92,92' name='elbowsY'/>",
        "  <property value='East_1' name='fromPort'/>",
        "  <property value='West_1' name='toPort'/>",
        "  <property value='success' name='label'/>",
        "</pageflow-object>",
        "</view-properties>"
    })
public class Controller extends PageFlowController
{
    private String hiddenValue = "Page Flow Hidden Value";
    private String value = "No Value Set";

    public String getHiddenValue()
    {
        return hiddenValue;
    }

    public void setHiddenValue(String hiddenValue)
    {
        this.hiddenValue = hiddenValue;
    }

    public String getValue()
    {
        return value;
    }

    public void setValue(String value)
    {
        this.value = value;
    }

    // Uncomment this declaration to access Global.app.
    // 
    //     protected global.Global globalApp;
    // 

    // For an example of page flow exception handling see the example "catch" and "exception-handler"
    // annotations in {project}/WEB-INF/src/global/Global.app

    @Jpf.Action(
        forwards = {
            @Jpf.Forward(
                name = "success",
                path = "index.jsp") 
        })
    protected Forward begin()
    {
        return new Forward( "success" );
    }

    @Jpf.Action(
        forwards = {
            @Jpf.Forward(
                name = "success",
                path = "index.jsp") 
        })
    protected Forward post(HiddenForm form)
    {
        value = form.getHidden();
        return new Forward("success");
    }

    /**
     * FormData get and set methods may be overwritten by the Form Bean editor.
     */
    public static class HiddenForm implements Serializable
    {
        private String hidden;

        public void setHidden(String hidden)
        {
            this.hidden = hidden;
        }

        public String getHidden()
        {
            return this.hidden;
        }
    }
}
