<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Bug 30458
        </title>
    </head>
    <netui:body>
        <netui-data:getData resultId="foo" value="${ pageFlow.stuff}" />
        <netui-data:repeater dataSource="pageScope.foo">
            <netui-data:repeaterHeader><table cellspacing="0" cellpadding="4" border="1"
                class="tablebody" ></netui-data:repeaterHeader>
            <netui-data:repeaterItem>
                <tr>
                    <td><netui:span value="${container.item}"></netui:span></td>
                </tr>
            </netui-data:repeaterItem>
            <netui-data:repeaterFooter></table></netui-data:repeaterFooter>
        </netui-data:repeater>
    </netui:body>
</netui:html>
