<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://handlers" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://handlers" xmlns:intf="http://handlers" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.3
Built on Oct 05, 2005 (05:23:37 EDT)-->

   <wsdl:message name="echoStringHeaderRequest">

      <wsdl:part name="inputHeader" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="echoStringHeaderResponse">

      <wsdl:part name="inputHeader" type="xsd:string"/>

   </wsdl:message>

   <wsdl:portType name="HandlerRpcLitEndpoint">

      <wsdl:operation name="echoStringHeader" parameterOrder="inputHeader">

         <wsdl:input message="impl:echoStringHeaderRequest" name="echoStringHeaderRequest"/>

         <wsdl:output message="impl:echoStringHeaderResponse" name="echoStringHeaderResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="HandlerRpcLitEndpointSoapBinding" type="impl:HandlerRpcLitEndpoint">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="echoStringHeader">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="echoStringHeaderRequest">

            <wsdlsoap:body namespace="http://handlers" parts="" use="literal"/>

            <wsdlsoap:header message="impl:echoStringHeaderRequest" namespace="http://handlers" part="inputHeader" use="literal">

            </wsdlsoap:header>

         </wsdl:input>

         <wsdl:output name="echoStringHeaderResponse">

            <wsdlsoap:body namespace="http://handlers" parts="null" use="literal"/>

            <wsdlsoap:header message="impl:echoStringHeaderResponse" namespace="http://handlers" part="inputHeader" use="literal">

            </wsdlsoap:header>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="HandlerRpcLitEndpointService">

      <wsdl:port binding="impl:HandlerRpcLitEndpointSoapBinding" name="HandlerRpcLitEndpoint">

         <wsdlsoap:address location="http://localhost:8080/ServiceControlDRT/handlers/HandlerRpcLitEndpoint.jws"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
