<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Return To Action - nested
        </title>
    </head>
    <body>
        <h3>Return To Action - nested</h3>
        
        <netui:anchor action="returnToPreviousAction">returnTo="previousAction" on nesting page flow</netui:anchor>
        <br>
        <netui:anchor action="returnToAction">returnTo="action" on nesting page flow</netui:anchor>
    </body>
</netui:html>
