<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Web Application Page
        </title>
    </head>
    <netui:body>
    <h4>Anchor bound inside a repeater</h4>
    <p style="color:green">
    This test has two parts.  the first is an anchor found inside of a repeater.  The repeater is bound
    to a list of actions which are bound as the action for the anchor and the label of the anchor.  When any
    of these are preseed, the last action will be updated.
    </p>
    <p style="color:green">
    The second part of the test is the errors.  Pushing this link leads to a page of errors.
    </p>
    <netui-data:repeater dataSource="pageFlow.actions">
            <netui-data:repeaterHeader><ul></netui-data:repeaterHeader>
            <netui-data:repeaterItem>
                <li>
                <netui:anchor action="${container.item}">
                    <netui:span value="${container.item}"></netui:span>
                </netui:anchor>
                </li>
            </netui-data:repeaterItem>
            <netui-data:repeaterFooter></ul></netui-data:repeaterFooter>
    </netui-data:repeater>
    <netui:anchor action="goErrors">Errors</netui:anchor><br>
    <hr>
    <b>Last Action:</b>&nbsp;<netui:span value="${pageFlow.lastAction}"/>
    </netui:body>
</netui:html>
