<!--Generated by Weblogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
<head>
    <netui:base />
</head>
<body>
    <netui:form action="formAction" >
        <table>
            <tr>
                <th align="right" valign="top">Name:</th>
                <td align="left"><netui:textBox dataSource="actionForm.name" size="36" maxlength="36"></netui:textBox></td>
                
                <td style="color:red;">
                    <netui:error key="name"></netui:error>
                    &nbsp;
                </td>
            </tr>
            <tr>
                <th align="right" valign="top">Type:</th>
                <td align="left"><netui:textBox dataSource="actionForm.type" size="36" maxlength="36"></netui:textBox></td>
                
                <td style="color:red;">
                    <netui:error key="te"></netui:error>
                </td>
            </tr>
            <tr>
                <td align="center" colspan="3">
                    <netui:button value="Submit"></netui:button>&nbsp;
                </td>
            </tr>
            <tr>
                <td colspan="3" align="center">
                    <netui:errors></netui:errors>
                </td>
            </tr>
        </table>
    </netui:form>
    
</body>
</netui:html>
