<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@page import="org.apache.beehive.netui.pageflow.PageFlowUtils"%>
<%@ page import="javax.servlet.ServletContext"%>
<%@ page import="javax.servlet.http.HttpServletRequest"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            PageFlowUtils - isSecureResource
        </title>
    </head>
    <body>
        <% ServletContext servletContext = pageContext.getServletContext(); %>
        <% HttpServletRequest req = (HttpServletRequest) pageContext.getRequest(); %>

        <code>isSecureResource( "/miniTests/pageFlowUtils/secure/foo.jsp", servletContext )</code>:
            <%= PageFlowUtils.isSecureResource( "/miniTests/pageFlowUtils/secure/foo.jsp", servletContext, req) %><br>

        <code>isSecureResource( "/miniTests/pageFlowUtils/secureFoo.do", servletContext )</code>:
            <%= PageFlowUtils.isSecureResource( "/miniTests/pageFlowUtils/secureFoo.do", servletContext, req ) %><br>

        <code>isSecureResource( "/miniTests/pageFlowUtils/foo.pageFlowUtilsSecure", servletContext )</code>:
            <%= PageFlowUtils.isSecureResource( "/miniTests/pageFlowUtils/foo.pageFlowUtilsSecure", servletContext, req ) %><br>
        
        <br>
        
        <code>isSecureResource( "/miniTests/pageFlowUtils/unsecure/foo.jsp", servletContext )</code>:
            <%= PageFlowUtils.isSecureResource( "/miniTests/pageFlowUtils/unsecure/foo.jsp", servletContext, req ) %><br>

        <code>isSecureResource( "/miniTests/pageFlowUtils/unsecureFoo.do", servletContext )</code>:
            <%= PageFlowUtils.isSecureResource( "/miniTests/pageFlowUtils/unsecureFoo.do", servletContext, req ) %><br>

        <code>isSecureResource( "/miniTests/pageFlowUtils/foo.pageFlowUtilsUnsecure", servletContext )</code>:
            <%= PageFlowUtils.isSecureResource( "/miniTests/pageFlowUtils/foo.pageFlowUtilsUnsecure", servletContext, req ) %><br>
        
        <br>
        
        <code>isSecureResource( "/miniTests/pageFlowUtils/nothing/foo.jsp", servletContext )</code>:
            <%= PageFlowUtils.isSecureResource( "/miniTests/pageFlowUtils/nothing/foo.jsp", servletContext, req ) %><br>

        <code>isSecureResource( "/miniTests/pageFlowUtils/nothingFoo.do", servletContext )</code>:
            <%= PageFlowUtils.isSecureResource( "/miniTests/pageFlowUtils/nothingFoo.do", servletContext, req ) %><br>

        <code>isSecureResource( "/miniTests/pageFlowUtils/foo.pageFlowUtilsNothing", servletContext )</code>:
            <%= PageFlowUtils.isSecureResource( "/miniTests/pageFlowUtils/foo.pageFlowUtilsNothing", servletContext, req ) %><br>
        
        
                
        <br>
        <br>
        <netui:anchor action="begin">go back</netui:anchor>
    </body>
</netui:html>
