<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>Sample Application Resutl Page</title>
    </head>
    <body>
        Prop1: <netui:span value="${pageFlow.prop1}"></netui:span><br>
        Prop2: <netui:span value="${pageFlow.prop2}"></netui:span><br>
        Form: <netui:span value="${pageFlow.formValue}"></netui:span><br>
        <p>
        <netui:anchor action="begin">back</netui:anchor>
    </body>
</netui:html>
