<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Bug 34998
        </title>
    </head>
    <netui:body>
        <h4>Bug 34998</h4>
        <p style="color:green">
        This test simply posts a textArea and the sets a text property on the pageFlow.  The results
        will then display that value.  The resulting text should be exactly the same as entered into the textArea.
        </p>
        <netui:form action="EnterName" focus="" tagId="FormOne">
            <table>
                <tr>
                    <td>Text:</td>
                    <td>
                    <netui:textArea dataSource="actionForm.text"></netui:textArea>
                    </td>
                </tr>
            </table>
            <netui:button value="Enter"></netui:button>
        </netui:form>
    </netui:body>
</netui:html>
