<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<netui:html>
    <head>
        <title>
            Web Application Page
        </title>
    </head>
    <body>
        <netui:form action="upload" enctype="multipart/form-data">
            File: <netui:fileUpload dataSource="actionForm.file" readonly="false" size="60"/>
                <netui:error key="file"/>
            <br>
            Label: <netui:textBox dataSource="actionForm.label"/>
            <br>
            <br>
            <netui:button value="submit"/>
        </netui:form>

        <br>

        <c:if test="${!pageFlow.scoped}">
            <netui:anchor href="MockPortal.jsp">try this in MockPortal</netui:anchor>
        </c:if>
        <c:if test="${pageFlow.scoped}">
            <netui:anchor href="uploadController.jpf">try this outside of MockPortal</netui:anchor>
        </c:if>
    </body>
</netui:html>
