<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Bug 22957
        </title>
    </head>
    <netui:body>
         <netui:form action="foo"> 
            <netui:anchor formSubmit="true">Create</netui:anchor> 
        </netui:form>
        <netui:span value="${pageFlow.lastAction}"/>
    </netui:body>
</netui:html>
