<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
<%
    try
    {
%>
    <body>
      <netui-data:repeater dataSource="pageFlow.data">
      <netui-data:repeaterHeader><ul></netui-data:repeaterHeader>
      <netui-data:repeaterItem><li><netui:span value="${container.foo}"/></li>
        </netui-data:repeaterItem>
      <netui-data:repeaterFooter></ul></netui-data:repeaterFooter>
      </netui-data:repeater>
<%
    }
    catch(Exception e)
    {
        if(e instanceof javax.servlet.jsp.el.ELException)
            out.write("success -- caught ELException; assumed to be related to missing {container.foo}");
        else out.write("fail -- exception was not servlet exception");
    }
%>
    </body>
</netui:html>
