<!--Generated by Weblogic Workshop-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>

<html>
   <head>
      <title><netui-template:attribute name="title"/></title>
   </head>
      <body>
      <h3 align="center"><netui-template:attribute name="heading"/></h3>
      <hr width="95%"/>
      <br/>
      <netui-data:declarePageInput name="string" type="java.lang.String" />
      <center>
         PageInput context value in the template:
         <font color="blue">
            <netui:span value="${pageInput.string}" />
         </font>
         <br/><br/>
      </center>
      <netui-template:includeSection name="bodySection">
      </netui-template:includeSection>
   </body>
</html>
