<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Bug 33322
        </title>
    </head>
    <netui:body>
    Date: <netui:span value="${pageFlow.foo}"><netui:formatDate pattern="MM/dd/yyyy"/></netui:span><br />
    </netui:body>
</netui:html>
