    <!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
    <netui-template:template templatePage="/resources/jsp/template.jsp">
        <netui-template:section name="bodySection">
            <netui:form action="someAction" enctype="multipart/form-data">
                <table>
                    <tr valign="top">
                        <td>
                            FormProp:
                        </td>
                        <td>
                            <netui:textBox dataSource="actionForm.formProp"/>
                        </td>
                    </tr>
                    <tr valign="top">
                        <td>
                            PfProp:
                        </td>
                        <td>
                            <netui:textBox dataSource="pageFlow.pfProp"/>
                        </td>
                    </tr>
                    <tr valign="top">
                        <td>
                            FormFile:
                        </td>
                        <td>
                            <netui:fileUpload dataSource="actionForm.formFile" readonly="false" size="60"/>
                        </td>
                    </tr>
                    <tr valign="top">
                        <td>
                            PfFile:
                        </td>
                        <td>
                            <netui:fileUpload dataSource="pageFlow.pfFile" readonly="false" size="60"/>
                        </td>
                    </tr>
                </table>
                <br/>
                &nbsp;
                <netui:button value="submit"/>
                <netui:button value="submit to non-form action" action="nonFormAction"/>
                <netui:button value="execute another action" action="someOtherAction"/>
            </netui:form>
            
            <netui:anchor action="reset">reset data</netui:anchor>
            <br>
            <c:if test="${!pageFlow.scoped}">
                <netui:anchor href="MockPortal.jsp">try this in MockPortal</netui:anchor>
            </c:if>
            <c:if test="${pageFlow.scoped}">
                <netui:anchor href="multipartRequestController.jpf">try this outside of MockPortal</netui:anchor>
            </c:if>

        </netui-template:section>
    </netui-template:template>
