    <!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
    <netui-template:template templatePage="/resources/jsp/template.jsp">
        <netui-template:section name="bodySection">
            <netui:form action="someAction">
                <table>
                    <tr valign="top">
                        <td>
                            FormProp:
                        </td>
                        <td>
                            <netui:span value="${actionForm.formProp}"/>
                        </td>
                    </tr>
                    <tr valign="top">
                        <td>
                            PfProp:
                        </td>
                        <td>
                            <netui:span value="${pageFlow.pfProp}"/>
                        </td>
                    </tr>
                    <tr valign="top">
                        <td>
                            FormFile:
                        </td>
                        <td>
                            <netui:span value="${actionForm.fileContents}"/>
                        </td>
                    </tr>
                    <tr valign="top">
                        <td>
                            PfFile:
                        </td>
                        <td>
                            <netui:span value="${pageFlow.fileContents}"/>
                        </td>
                    </tr>
                </table>
                <br/>
            </netui:form>
            
            <br>
            <netui:anchor action="begin">start over</netui:anchor>

        </netui-template:section>
    </netui-template:template>
