<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@page import="org.apache.beehive.netui.pageflow.PageFlowUtils"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Nested (PageFlowUtils Tests)
        </title>
    </head>
    <body>
        <h3>Nested (PageFlowUtils Tests)</h3>
        
        
        <code>getPageFlowStack( request ).size()</code>:
            <%= PageFlowUtils.getPageFlowStack( request ).size() %><br>

        <code>getNestingPageFlow( request )</code>:
            <%= PageFlowUtils.getNestingPageFlow( request ).getClass().getName() %><br>

        <br>
        <br>
        <netui:anchor action="done">
            Exit nested
        </netui:anchor>
    </body>
</netui:html>
