<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>

<netui:html>
    <head>
        <title>
            ModuleConfigLocator
        </title>
    </head>
    <body>
        <h3>ModuleConfigLocator</h3>
        
        <i>moduleConfigLocator.Locator1 and moduleConfigLocator.Locator2 are registered in web.xml</i>
        <br>
        <br>
        <a href="<%= request.getContextPath() %>/foo/begin.do">test Locator1</a>
        <br>
        <a href="<%= request.getContextPath() %>/bar/begin.do">test Locator2</a>
    </body>
</netui:html>
