<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>

<netui:html>
    <head>
        <title>
            ModuleConfigLocator - Locator2
        </title>
    </head>
    <body>
        <h3>ModuleConfigLocator - Locator2</h3>
        
        <i>Got here through moduleConfigLocator.Locator2</i>
        <br>
        <br>
        <a href="<%= request.getContextPath() %>/miniTests/moduleConfigLocator/index.jsp">go back</a>
    </body>
</netui:html>
