<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Web Application Page
        </title>
    </head>
    <netui:body>
        <h4>Hidden Using dataInput</h4>
        <p style="color:green">
        This test will bind a value from the dataInput attribute which will be posted to the actionForm.
        The value then is displayed in the hidden value below.  You should hit input to see the posted
        value <b>Page Flow Hidden Value</b>.
        </p>
        <netui:form action="post">
            <netui:hidden dataSource="actionForm.hidden" dataInput="${pageFlow.hiddenValue}"/>           
            <netui:button value="post" type="submit"/>
        </netui:form>
        Hidden: <netui:span value="${pageFlow.value}"/> 
        <hr/>
     </netui:body>
</netui:html>
