<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Bug 34263
        </title>
    </head>
    <netui:body>
        <netui:form action="EnterName" focus="" tagId="FormOne">
            <table>
                <tr>
                    <td>LastName:</td>
                    <td>
                    <netui:textBox dataSource="actionForm.lastName"></netui:textBox>
                    </td>
                </tr>
                <tr>
                    <td>FirstName:</td>
                    <td>
                    <netui:textBox dataSource="actionForm.firstName"></netui:textBox>
                    </td>
                </tr>
            </table>
            <netui:button value="Enter" tagId="NameEnter"></netui:button>
            <netui:button type="submit" value="Delete" action="DeleteName" tagId="NameDelete"></netui:button>
        </netui:form>
        <hr />
        <netui:span value="${pageFlow.action}"/>
    </netui:body>
</netui:html>
