<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
  <head>
    <title>Web Application Page</title>
  </head>
  <body>
        <p>
        <netui:form action="testAction">
            <table>
                <tr valign="top">
                    <td>
                    <netui:checkBoxGroup dataSource="pageFlow.boxes" optionsDataSource="${pageFlow.list1}" />
                    </td>
                </tr>
            </table>
            <br/>&nbsp;
            <netui:button value="testAction" type="submit"/>
        </netui:form>
        
        
        </p>
  </body>
</netui:html>
