<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Errors Tag 4
        </title>
    </head>
    <body>
        <h3>Errors Tag 4</h3>
        
        <netui:errors bundleName="rootMessages/" />
        
        <br>
        <netui:anchor action="goPrev">go back</netui:anchor>
    </body>
</netui:html>
