<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Web Application Page
        </title>
    </head>
    <body>
        <h4>String Values - Full Repeater</h4>
        <netui-data:repeater dataSource="pageFlow.stringValues">
            <netui-data:repeaterHeader>
                <ul>
            </netui-data:repeaterHeader>
            <netui-data:repeaterItem>
                <li><netui:span value="${container.item}"></netui:span></li>
            </netui-data:repeaterItem>
            <netui-data:repeaterFooter></ul></netui-data:repeaterFooter>
        </netui-data:repeater>
        <hr />
        <h4>String Values - Simple Repeater</h4>
        <ul>
        <netui-data:repeater dataSource="pageFlow.stringValues">
            <li><netui:span value="${container.item}"></netui:span></li>
        </netui-data:repeater>
        </ul>
        <hr />
        <h4>List Values - Full Repeater</h4>
        <netui-data:repeater dataSource="pageFlow.listValues">
            <netui-data:repeaterHeader>
                <ul>
            </netui-data:repeaterHeader>
            <netui-data:repeaterItem>
                <li><netui:span value="${container.item}"></netui:span></li>
            </netui-data:repeaterItem>
            <netui-data:repeaterFooter></ul></netui-data:repeaterFooter>
        </netui-data:repeater>
        <hr />
        <h4>List Values - Simple Repeater</h4>
        <ul>
        <netui-data:repeater dataSource="pageFlow.listValues">
            <li><netui:span value="${container.item}"></netui:span></li>
         </netui-data:repeater>
        </ul>
    </body>
</netui:html>
