<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@page import="org.apache.beehive.netui.pageflow.PageFlowUtils"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<netui:html>
    <head>
        <title>return-to test</title>
    </head>

    <body>
        <h3>return-to test</h3>
        <br/>
        input1: <font color="blue"><%= PageFlowUtils.getPageInput( "input1", request ) %></font>
        <br>
        input2: <font color="blue"><%= PageFlowUtils.getPageInput( "input2", request ) %></font>
        <br>
        <br>
        Leaving "foo" blank will make validation fail.
        
        <netui:form action="input">
            <table class="tablebody">
                <tr class="tablebody">
                    <td>foo:</td>
                    <td>
                        <netui:textBox dataSource="actionForm.foo"/>
                        <netui:error key="foo"/>
                    </td>
                </tr>
                <tr class="tablebody">
                    <td>bar:</td>
                    <td>
                        <netui:textBox dataSource="actionForm.bar"/>
                    </td>
                </tr>
            </table>
            <br/>&nbsp;
            <netui:button value="Submit" type="submit"/>

            <br>
            <br>
            <netui:anchor action="returnToCurrentPage">return-to currentPage</netui:anchor>
            <br>
            <netui:anchor action="returnToCurrentPageWithForm" formSubmit="true">return-to currentPage (keep form)</netui:anchor>
            <br>
            <netui:anchor action="returnToCurrentPageOverrideInputs">return-to currentPage (override page inputs)</netui:anchor>
            <br>
            <netui:anchor action="returnToCurrentPageOverrideForm">return-to currentPage (override form)</netui:anchor>
            <br>
            <br>
            <netui:anchor action="globalReturnToCurrentPage">global-action return-to currentPage</netui:anchor>
            <br>
            <netui:anchor action="globalReturnToCurrentPageWithForm" formSubmit="true">global-action return-to currentPage (keep form)</netui:anchor>
            <br>
            <netui:anchor action="globalReturnToCurrentPageOverrideInputs">global-action return-to currentPage (override page inputs)</netui:anchor>
            <br>
            <netui:anchor action="globalReturnToCurrentPageOverrideForm">global-action return-to currentPage (override form)</netui:anchor>
            <br>
            <br>
            <netui:anchor action="globalReturnToPage">global-action return-to page</netui:anchor>
            <br>
            <netui:anchor action="globalReturnToPageWithForm" formSubmit="true">global-action return-to page (keep form)</netui:anchor>
            <br>
            <netui:anchor action="globalReturnToPageOverrideInputs">global-action return-to page (override page inputs)</netui:anchor>
            <br>
            <netui:anchor action="globalReturnToPageOverrideForm">global-action return-to page (override form)</netui:anchor>
            <br>
            <br>
            <netui:anchor action="goNested">go to nested page flow</netui:anchor>          
            <br>
            <br>
            <netui:anchor href="returnToAction/returnToActionController.jpf">test returnTo="previousAction" and returnTo="action"</netui:anchor>
            <br>
            <br>
            <netui:anchor action="begin">start over</netui:anchor>          

        </netui:form>
    </body>
</netui:html>
