<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Web Application Page
        </title>
    </head>
    <body>
        <p>
            <netui:anchor action="returnToPreviousPage">return-to previousPage</netui:anchor>
            <br>
            <netui:anchor action="returnToPreviousPageOverrideForm">return-to previousPage (override form)</netui:anchor>
            <br>
            <netui:anchor action="returnToPreviousPageOverrideInputs">return-to previousPage (override page inputs)</netui:anchor>
            <br>
            <netui:anchor action="globalReturnToPreviousPage">global-action return-to previousPage</netui:anchor>
            <br>
            <netui:anchor action="globalReturnToPreviousPageOverrideForm">global-action return-to previousPage (override form)</netui:anchor>
            <br>
            <netui:anchor action="globalReturnToPreviousPageOverrideInputs">global-action return-to previousPage (override page inputs)</netui:anchor>
            <br>
            <netui:anchor action="returnToPage">return-to page</netui:anchor>
            <br>
            <netui:anchor action="returnToPageOverrideForm">return-to page (override form)</netui:anchor>
            <br>
            <netui:anchor action="returnToPageOverrideInputs">return-to page (override page inputs)</netui:anchor>  
            <br>
            <br>
            <netui:anchor action="goNested">go to nested page flow</netui:anchor>          
            <br>
            <br>
            <netui:anchor action="begin">start over</netui:anchor>
        </p>
    </body>
</netui:html>
