/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * $Header:$
 */
// ------------------------------------------------------------------------------
//  Generated by WebLogic Workshop
// 
//  Created on: Fri Aug 08 17:31:48 MDT 2003
//  By: dolander
// -----------------------------------------------------------------------------
package javascript.jsAllScript;
import org.apache.beehive.netui.pageflow.Forward;
import org.apache.beehive.netui.pageflow.PageFlowController;
import org.apache.beehive.netui.pageflow.annotations.Jpf;

import java.io.Serializable;

/**
 * @jpf:controller
 * @jpf:view-properties view-properties::
 * <!-- This data is auto-generated. Hand-editing this section is not recommended. -->
 * <view-properties>
 * <pageflow-object id="pageflow:/jsAllScript/Controller.jpf"/>
 * <pageflow-object id="action:begin.do">
 *   <property value="360" name="x"/>
 *   <property value="40" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="action:submit.do#jsAllScript.Controller.NameBean">
 *   <property value="360" name="x"/>
 *   <property value="100" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="action:foobar.do#jsAllScript.Controller.NameBean">
 *   <property value="360" name="x"/>
 *   <property value="160" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="action:baz.do#jsAllScript.Controller.NameBean">
 *   <property value="360" name="x"/>
 *   <property value="220" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="action:imageSubmit.do#jsAllScript.Controller.NameBean">
 *   <property value="360" name="x"/>
 *   <property value="280" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="action-call:@page:index.jsp@#@action:baz.do#jsAllScript.Controller.NameBean@">
 *   <property value="216,270,270,324" name="elbowsX"/>
 *   <property value="123,123,212,212" name="elbowsY"/>
 *   <property value="East_2" name="fromPort"/>
 *   <property value="West_1" name="toPort"/>
 * </pageflow-object>
 * <pageflow-object id="action-call:@page:index.jsp@#@action:submit.do#jsAllScript.Controller.NameBean@">
 *   <property value="216,270,270,324" name="elbowsX"/>
 *   <property value="112,112,92,92" name="elbowsY"/>
 *   <property value="East_1" name="fromPort"/>
 *   <property value="West_1" name="toPort"/>
 * </pageflow-object>
 * <pageflow-object id="action-call:@page:index.jsp@#@action:begin.do@">
 *   <property value="216,270,270,324" name="elbowsX"/>
 *   <property value="101,101,43,43" name="elbowsY"/>
 *   <property value="East_0" name="fromPort"/>
 *   <property value="West_2" name="toPort"/>
 * </pageflow-object>
 * <pageflow-object id="action-call:@page:index.jsp@#@action:imageSubmit.do#jsAllScript.Controller.NameBean@">
 *   <property value="216,270,270,324" name="elbowsX"/>
 *   <property value="123,123,272,272" name="elbowsY"/>
 *   <property value="East_2" name="fromPort"/>
 *   <property value="West_1" name="toPort"/>
 * </pageflow-object>
 * <pageflow-object id="page:index.jsp">
 *   <property value="180" name="x"/>
 *   <property value="120" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="action-call:@page:Results.jsp@#@action:begin.do@">
 *   <property value="524,460,460,396" name="elbowsX"/>
 *   <property value="132,132,32,32" name="elbowsY"/>
 *   <property value="West_1" name="fromPort"/>
 *   <property value="East_1" name="toPort"/>
 * </pageflow-object>
 * <pageflow-object id="page:Results.jsp">
 *   <property value="560" name="x"/>
 *   <property value="140" name="y"/>
 * </pageflow-object>
 * <pageflow-object id="forward:path#success#index.jsp#@action:begin.do@">
 *   <property value="324,270,270,216" name="elbowsX"/>
 *   <property value="32,32,112,112" name="elbowsY"/>
 *   <property value="West_1" name="fromPort"/>
 *   <property value="East_1" name="toPort"/>
 *   <property value="success" name="label"/>
 * </pageflow-object>
 * <pageflow-object id="forward:path#success#Results.jsp#@action:submit.do#jsAllScript.Controller.NameBean@">
 *   <property value="396,460,460,524" name="elbowsX"/>
 *   <property value="92,92,132,132" name="elbowsY"/>
 *   <property value="East_1" name="fromPort"/>
 *   <property value="West_1" name="toPort"/>
 *   <property value="success" name="label"/>
 * </pageflow-object>
 * <pageflow-object id="forward:path#success#Results.jsp#@action:foobar.do#jsAllScript.Controller.NameBean@">
 *   <property value="396,460,460,524" name="elbowsX"/>
 *   <property value="152,152,132,132" name="elbowsY"/>
 *   <property value="East_1" name="fromPort"/>
 *   <property value="West_1" name="toPort"/>
 *   <property value="success" name="label"/>
 * </pageflow-object>
 * <pageflow-object id="forward:path#success#Results.jsp#@action:baz.do#jsAllScript.Controller.NameBean@">
 *   <property value="396,460,460,524" name="elbowsX"/>
 *   <property value="212,212,132,132" name="elbowsY"/>
 *   <property value="East_1" name="fromPort"/>
 *   <property value="West_1" name="toPort"/>
 *   <property value="success" name="label"/>
 * </pageflow-object>
 * <pageflow-object id="forward:path#success#Results.jsp#@action:imageSubmit.do#jsAllScript.Controller.NameBean@">
 *   <property value="396,460,460,524" name="elbowsX"/>
 *   <property value="272,272,143,143" name="elbowsY"/>
 *   <property value="East_1" name="fromPort"/>
 *   <property value="West_2" name="toPort"/>
 *   <property value="success" name="label"/>
 * </pageflow-object>
 * <pageflow-object id="formbeanprop:jsAllScript.Controller.NameBean#lastName#java.lang.String"/>
 * <pageflow-object id="formbeanprop:jsAllScript.Controller.NameBean#firstName#java.lang.String"/>
 * <pageflow-object id="formbean:jsAllScript.Controller.NameBean"/>
 * </view-properties>
 * ::
 */
@Jpf.Controller(
    )
@Jpf.ViewProperties(
    value = {
        "<!-- This data is auto-generated. Hand-editing this section is not recommended. -->",
        "<view-properties>",
        "<pageflow-object id='pageflow:/jsAllScript/Controller.jpf'/>",
        "<pageflow-object id='action:begin.do'>",
        "  <property value='360' name='x'/>",
        "  <property value='40' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='action:submit.do#jsAllScript.Controller.NameBean'>",
        "  <property value='360' name='x'/>",
        "  <property value='100' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='action:foobar.do#jsAllScript.Controller.NameBean'>",
        "  <property value='360' name='x'/>",
        "  <property value='160' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='action:baz.do#jsAllScript.Controller.NameBean'>",
        "  <property value='360' name='x'/>",
        "  <property value='220' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='action:imageSubmit.do#jsAllScript.Controller.NameBean'>",
        "  <property value='360' name='x'/>",
        "  <property value='280' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='action-call:@page:index.jsp@#@action:baz.do#jsAllScript.Controller.NameBean@'>",
        "  <property value='216,270,270,324' name='elbowsX'/>",
        "  <property value='123,123,212,212' name='elbowsY'/>",
        "  <property value='East_2' name='fromPort'/>",
        "  <property value='West_1' name='toPort'/>",
        "</pageflow-object>",
        "<pageflow-object id='action-call:@page:index.jsp@#@action:submit.do#jsAllScript.Controller.NameBean@'>",
        "  <property value='216,270,270,324' name='elbowsX'/>",
        "  <property value='112,112,92,92' name='elbowsY'/>",
        "  <property value='East_1' name='fromPort'/>",
        "  <property value='West_1' name='toPort'/>",
        "</pageflow-object>",
        "<pageflow-object id='action-call:@page:index.jsp@#@action:begin.do@'>",
        "  <property value='216,270,270,324' name='elbowsX'/>",
        "  <property value='101,101,43,43' name='elbowsY'/>",
        "  <property value='East_0' name='fromPort'/>",
        "  <property value='West_2' name='toPort'/>",
        "</pageflow-object>",
        "<pageflow-object id='action-call:@page:index.jsp@#@action:imageSubmit.do#jsAllScript.Controller.NameBean@'>",
        "  <property value='216,270,270,324' name='elbowsX'/>",
        "  <property value='123,123,272,272' name='elbowsY'/>",
        "  <property value='East_2' name='fromPort'/>",
        "  <property value='West_1' name='toPort'/>",
        "</pageflow-object>",
        "<pageflow-object id='page:index.jsp'>",
        "  <property value='180' name='x'/>",
        "  <property value='120' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='action-call:@page:Results.jsp@#@action:begin.do@'>",
        "  <property value='524,460,460,396' name='elbowsX'/>",
        "  <property value='132,132,32,32' name='elbowsY'/>",
        "  <property value='West_1' name='fromPort'/>",
        "  <property value='East_1' name='toPort'/>",
        "</pageflow-object>",
        "<pageflow-object id='page:Results.jsp'>",
        "  <property value='560' name='x'/>",
        "  <property value='140' name='y'/>",
        "</pageflow-object>",
        "<pageflow-object id='forward:path#success#index.jsp#@action:begin.do@'>",
        "  <property value='324,270,270,216' name='elbowsX'/>",
        "  <property value='32,32,112,112' name='elbowsY'/>",
        "  <property value='West_1' name='fromPort'/>",
        "  <property value='East_1' name='toPort'/>",
        "  <property value='success' name='label'/>",
        "</pageflow-object>",
        "<pageflow-object id='forward:path#success#Results.jsp#@action:submit.do#jsAllScript.Controller.NameBean@'>",
        "  <property value='396,460,460,524' name='elbowsX'/>",
        "  <property value='92,92,132,132' name='elbowsY'/>",
        "  <property value='East_1' name='fromPort'/>",
        "  <property value='West_1' name='toPort'/>",
        "  <property value='success' name='label'/>",
        "</pageflow-object>",
        "<pageflow-object id='forward:path#success#Results.jsp#@action:foobar.do#jsAllScript.Controller.NameBean@'>",
        "  <property value='396,460,460,524' name='elbowsX'/>",
        "  <property value='152,152,132,132' name='elbowsY'/>",
        "  <property value='East_1' name='fromPort'/>",
        "  <property value='West_1' name='toPort'/>",
        "  <property value='success' name='label'/>",
        "</pageflow-object>",
        "<pageflow-object id='forward:path#success#Results.jsp#@action:baz.do#jsAllScript.Controller.NameBean@'>",
        "  <property value='396,460,460,524' name='elbowsX'/>",
        "  <property value='212,212,132,132' name='elbowsY'/>",
        "  <property value='East_1' name='fromPort'/>",
        "  <property value='West_1' name='toPort'/>",
        "  <property value='success' name='label'/>",
        "</pageflow-object>",
        "<pageflow-object id='forward:path#success#Results.jsp#@action:imageSubmit.do#jsAllScript.Controller.NameBean@'>",
        "  <property value='396,460,460,524' name='elbowsX'/>",
        "  <property value='272,272,143,143' name='elbowsY'/>",
        "  <property value='East_1' name='fromPort'/>",
        "  <property value='West_2' name='toPort'/>",
        "  <property value='success' name='label'/>",
        "</pageflow-object>",
        "<pageflow-object id='formbeanprop:jsAllScript.Controller.NameBean#lastName#java.lang.String'/>",
        "<pageflow-object id='formbeanprop:jsAllScript.Controller.NameBean#firstName#java.lang.String'/>",
        "<pageflow-object id='formbean:jsAllScript.Controller.NameBean'/>",
        "</view-properties>"
    })
public class Controller extends PageFlowController
{
    public String getAction() {
        return "foobar";
    }

    // Uncomment this declaration to access Global.app.
    // 
    //     protected global.Global globalApp;
    // 

    // For an example of page flow exception handling see the example "catch" and "exception-handler"
    // annotations in {project}/WEB-INF/src/global/Global.app

    /**
     * This method represents the point of entry into the pageflow
     * @jpf:action
     * @jpf:forward name="success" path="index.jsp"
     */
    @Jpf.Action(
        forwards = {
            @Jpf.Forward(
                name = "success",
                path = "index.jsp") 
        })
    protected Forward begin()
    {
        return new Forward( "success" );
    }

    /**
     * @jpf:action
     * @jpf:forward name="success" path="Results.jsp"
     */
    @Jpf.Action(
        forwards = {
            @Jpf.Forward(
                name = "success",
                path = "Results.jsp") 
        })
    protected Forward submit(NameBean form)
    {
        Forward f = new Forward("success");
        f.addPageInput("names",form);
        return f;
    }

    /**
     * @jpf:action
     * @jpf:forward name="success" path="Results.jsp"
     */
    @Jpf.Action(
        forwards = {
            @Jpf.Forward(
                name = "success",
                path = "Results.jsp") 
        })
    protected Forward foobar(NameBean form)
    {
        Forward f = new Forward("success");
        f.addPageInput("names",form);
        return f;
    }

    /**
     * @jpf:action
     * @jpf:forward name="success" path="Results.jsp"
     */
    @Jpf.Action(
        forwards = {
            @Jpf.Forward(
                name = "success",
                path = "Results.jsp") 
        })
    protected Forward baz(NameBean form)
    {
        Forward f = new Forward("success");
        f.addPageInput("names",form);
        return f;
    }

    /**
     * @jpf:action
     * @jpf:forward name="success" path="Results.jsp"
     */
    @Jpf.Action(
        forwards = {
            @Jpf.Forward(
                name = "success",
                path = "Results.jsp") 
        })
    protected Forward imageSubmit(NameBean form)
    {
        Forward f = new Forward("success");
        f.addPageInput("names",form);
        return f;
    }

    /**
     * FormData get and set methods may be overwritten by the Form Bean editor.
     */
    public static class NameBean implements Serializable
    {
        private String firstName;

        private String lastName;


        public void setLastName(String lastName)
        {
            this.lastName = lastName;
        }

        public String getLastName()
        {
            return this.lastName;
        }

        public void setFirstName(String firstName)
        {
            this.firstName = firstName;
        }

        public String getFirstName()
        {
            return this.firstName;
        }
    }
}
