<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Web Application Page
        </title>
    </head>
    <body>
        From Label: ("08/28/2003"):
        <netui:span value="08/28/2003"> 
            <netui:formatDate pattern="MM/dd/yyyy"/> 
        </netui:span> <br />
        From Label: ("08/28/03"):
        <netui:span value="08/28/03"> 
            <netui:formatDate pattern="MM/dd/yyyy"/> 
        </netui:span>  <br />
        From Label: ("08/28/72"):
        <netui:span value="08/28/72"> 
            <netui:formatDate pattern="MM/dd/yyyy"/> 
        </netui:span>  <br />
        From Label: ("08282003"):
        <netui:span value="08282003"> 
            <netui:formatDate pattern="MM/dd/yyyy"/> 
        </netui:span> <br />
        From Label: ("082803"):
        <netui:span value="082803"> 
            <netui:formatDate pattern="MM/dd/yyyy"/> 
        </netui:span>  <br />
        From Label: ("082872"):
        <netui:span value="082872"> 
            <netui:formatDate pattern="MM/dd/yyyy"/> 
        </netui:span>  <br />
        Repeater from String: 
        <netui-data:repeater dataSource="pageFlow.stringDates"> 
          <netui-data:repeaterItem> 
             <netui:span value="${container.item}"> 
              <netui:formatDate pattern="MM/dd/yy"/> 
             </netui:span> 
          </netui-data:repeaterItem> 
        </netui-data:repeater> 

    </body>
</netui:html>
