<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
    <head>
        <title>
            Fully-Readonly Page Flow
        </title>
    </head>
    <body>
        <h3>Fully-Readonly Page Flow</h3>
        
        <i>This page flow will blow up if ensureFailover is ever called.</i>
        <br>
        <br>
        <netui:anchor action="someAction">some action</netui:anchor>
        <br>
        <br>
        
        <netui:anchor action="done">
            Exit nested
        </netui:anchor>
    </body>
</netui:html>
