<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib prefix="netui" uri="http://beehive.apache.org/netui/tags-html-1.0"%>
<netui:html idScope="html">
    <head>
        <netui:base/>
    </head>
    <netui:body>
        <p style="color:green">This is a test of the ScriptBlock tag.  The
	script block generated will be placed after the framework generated
	javaScript.  This is necessary because the JavaScript here calls
	methods generated by the framework.
        </p>
        <span id="scopeOneSpan" />
        <netui:form tagId="form" action="post" focus="b1">
            <table>
                <tr valign="top">
                    <td>Text:</td>
                    <td>
                    <netui:textBox tagId="t1" dataSource="actionForm.text1" /><br>
                    <netui:textBox tagId="t2" dataSource="actionForm.text2" />
                    </td>
                </tr>
            </table>
            <br>
            <netui:button tagId="b1" value="Submit" />&nbsp;
            <netui:button tagId="b2" value="Override" action="override"/>&nbsp;

        </netui:form>
        <hr>
        Post Value: <netui:span tagId="postValue" value="${pageFlow.text}"/><br>
        Method: <netui:span tagId="method" value="${pageFlow.method}"/>
        <hr>
        <p id="javaOut"></p>

<netui:scriptBlock placement="after">
    // JavaScript from the page.  This should be placed after the
    // framework generated JavaScript

    var p = document.getElementById("javaOut");
    var s = document.getElementById("scopeOneSpan");

    var val = "<b>Document Access</b><br>";
    val = val + "JavaScript lookup real name is null: <b>" +
	(document["bean"] == null) + "</b><br>";
    val = val + "Form by name is null: <b>" +
        (document[lookupNameByTagId("form",s)] == null) + "</b><br>";


    val = val + "<br><b>ScopeId value</b><br>";
    val = val + "ScopeId: <b>" + getScopeId(s) + "</b><br>";

    val = val + "<br><b>NetUI Access Methods</b><br>";
    val = val + "TextBox 1 by id is null: <b>" +
        (document.getElementById(lookupIdByTagId("t1",s)) == null) + "</b><br>";
    val = val + "TextBox 1 by name is null: <b>" +
        (document["bean"][lookupNameByTagId("t1",s)] == null) + "</b><br>";

    p.innerHTML = val;
</netui:scriptBlock>
    </netui:body>
</netui:html>

  
